name: Maven Package

on:
 push:
 pull_request:

jobs:
  build:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
    - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 19
          target-folder: javadoc 
